### ISSUE TITLE
How to modify the font size ?

### ISSUE THREAD

**Issue by gywhitel** [Teraskull/bigsur-grub2-theme#4]
Hello, this is a fantastic grub theme. 
I found the font of OS is super tiny due to the high resolution of my screen. Is there any way to increase the font size? That would be perfect.

**Comment by Teraskull** [comment]
@gywhitel Of course there is. Play around with font sizes in `theme.txt`. I can't help with exact sizes because I only own a fullHD monitor.

**Comment by rahaaatul** [comment]
@Teraskull how to change the font?
