### ISSUE TITLE
Feat: (Suggestion) Icon support for nixos

### ISSUE THREAD

**Issue by im-notpua** [Teraskull/bigsur-grub2-theme#9]
Hey you seem to have icons, for all major distros including, lfs (linux from scratch). But I would like to have support for Nixos.

I could manually add it locally, but integrating that with nixos is a hell.

You can find a decent logo matching your theme in other theme pages, like [this ](https://github.com/AdisonCavani/distro-grub-themes/blob/master/assets/icons/nix.png) 

Thank You.

**Comment by Teraskull** [comment]
Done in 5bf0a97, thanks for the suggestion!

**Comment by im-notpua** [comment]
Hey @Teraskull , sorry for late response, but the file name should be `nixos.png` not `nix.png`. [Here's](https://pastebin.com/j5hTCYp6) my autogenerated grub.cfg for instance.

**Comment by Teraskull** [comment]
Thanks @im-notpua , fixed in b80ac7ee396de54a09e8693b2d86a8b77b1d5098!
